[package]
name = "radicle-dag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = { version = "1.8.0" }

[dev-dependencies]
qcheck = { version = "1" }
qcheck-macros = { version = "1" }
